//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADMIN
    {
        
        public int MaQuanTri { get; set; }
        [Required(ErrorMessage ="Chưa nhập thông tin tên quản trị")]
        public string TenQuanTri { get; set; }
        [Required(ErrorMessage = "Chưa nhập thông tin tên đăng nhập")]
        public string TenDangNhap { get; set; }
        [Required(ErrorMessage = "Chưa nhập thông tin mật khẩu")]
        public string MatKhau { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> QuyenTruyCap { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
