//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_SAN_PHAM
    {
        public int MaCTSP { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public string Mau { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
