//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.ANH_SAN_PHAM = new HashSet<ANH_SAN_PHAM>();
            this.CHI_TIET_DON_HANG = new HashSet<CHI_TIET_DON_HANG>();
        }
    
        public int MaSanPham { get; set; }
        public int MaCTDM { get; set; }
        public string TenSanPham { get; set; }
        public string TieuDeSanPham { get; set; }
        public Nullable<int> GiaSanPham { get; set; }
        public string ManHinh { get; set; }
        public string Cpu { get; set; }
        public string Ram { get; set; }
        public string HeDieuHanh { get; set; }
        public string CameraChinh { get; set; }
        public string CameraPhu { get; set; }
        public string BoNhoTrong { get; set; }
        public string TheNhoNgoai { get; set; }
        public string Blutooth { get; set; }
        public string DungLuongPin { get; set; }
        public Nullable<int> SoLuongTrongKho { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public string CheDoBaoHanh { get; set; }
        public string KhuyenMai { get; set; }
        public string TieuDeTinTuc { get; set; }
        public string NoiDungTinTuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANH_SAN_PHAM> ANH_SAN_PHAM { get; set; }
        public virtual CHI_TIET_DANH_MUC CHI_TIET_DANH_MUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_DON_HANG> CHI_TIET_DON_HANG { get; set; }
    }
}
