//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_TUC_SAN_PHAM
    {
        public int TTSP_Id { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public string TieuDeTinTuc { get; set; }
        public string AnhTinTuc { get; set; }
        public string NoiDungTinTuc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
