//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_TUC
    {
        public int MaTinTuc { get; set; }
        public string TenTinTuc { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TacGia { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
